### ISSUE TITLE
Adding boolean tick-boxes to registration form

### ISSUE THREAD

**Issue by anoopjt** [fahad-israr/forms-in-node-js#4]
We need the following boolean tick boxes at the top of the attend registration page and make changes to the schema. This is in addition to fixing the field name of the schema, named "numbers". 

Necessary conditions to take part in the virtual workshop
1. Have a laptop or a desktop computer to attend the virtual workshop
2. Internet connectivity with decent bandwidth
3. A functional web-camera
4. A microphone and a headphone 

@fahad-israr

**Comment by fahad-israr** [comment]
@Commit 
https://github.com/fahad-israr/forms-in-node-js/commit/6215d2081d21b1d3209bc5466b8c1000512daa0c

added needed form elements

**Comment by fahad-israr** [comment]
#Resolved  @Commit: 6215d20
